# Generated by Django 5.0.1 on 2025-11-23 13:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('profile_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(help_text='Full name in Arabic/English', max_length=200)),
                ('national_id', models.CharField(help_text='National ID (10 digits)', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Must be 10 digits')])),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture for visual identification', null=True, upload_to='profiles/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(help_text='License plate number (e.g., ABC 1234)', max_length=20)),
                ('plate_letters', models.CharField(help_text='Plate letters in Arabic', max_length=10)),
                ('car_icon', models.CharField(default='🚗', help_text='Emoji icon for car type', max_length=10)),
                ('car_name', models.CharField(blank=True, help_text="Friendly name (e.g., 'My Red Car')", max_length=100)),
                ('car_color', models.CharField(blank=True, help_text='Car color for visual identification', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary car for quick selection')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_plates', to='lowaah_app.userprofile')),
            ],
            options={
                'verbose_name': 'Car Plate',
                'verbose_name_plural': 'Car Plates',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
